### ISSUE TITLE
the mistery of glob pattern on windows

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/rocket-rental#11]
`build-server.ts` is used during build process
until today i did not try to build an app in the workshops, since the app always starts in development mode, only for testing we need to run the build process.

`glob.sync` work for me on windows for `rocket-rental` without the fix of replacing `\` with `/`, i guess it is just the length of the path.
in both workshop the path is deeper.

i think it is better to apply the same patch here as well.

one more thing, `glob` is missing from rocket-rental dependencies/devdependencies as well as for all workshop apps

**Comment by kentcdodds** [comment]
I'll look into this 👍

**Comment by onemen** [comment]
same apply to chokidar


![chokidar](https://user-images.githubusercontent.com/3650909/236132435-2eba516d-7ec7-4a1c-8c46-24702adb6cbf.png)

**Comment by kentcdodds** [comment]
This is no longer actively maintained, so I'm closing this issue. If you want an up-to-date example of a Remix app that builds on top of what was done here, check [the Epic Stack](https://github.com/epicweb-dev/epic-stack).
