### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by kirandash** [epicweb-dev/rocket-rental#25]
Env:
Node: 18.15.0

I am getting the following error on running `npm run dev`

<img width="1433" alt="image" src="https://github.com/epicweb-dev/rocket-rental/assets/13310363/2aa5a8cd-8bf5-40f1-9d76-95a9a2e791a8">

**Comment by kentcdodds** [comment]
This is no longer actively maintained, so I'm closing this issue. If you want an up-to-date example of a Remix app that builds on top of what was done here, check [the Epic Stack](https://github.com/epicweb-dev/epic-stack).
